[build]
builder = "NIXPACKS"
nixPkgs = ["nodejs-20_x"]
buildCommand = "npm install && npx nx build backend"

[deploy]
startCommand = "node apps/backend/dist/main.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10