[build]
builder = "NIXPACKS"
nixPkgs = ["nodejs-20_x"]
buildCommand = "cd ../.. && npm install && npx nx build backend && cp -r apps/backend/dist ."

[deploy]
startCommand = "node dist/main.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10